FORMAT: 1A

# Bonnier OTT: CAPI
Bonnier OTT: CAPI 

# Group Android
Android related resources

## Content [/android/1.1/page/{id}]

+ Parameters

    + id (string, `home`) ... An unique identifier (as defined in AppGrid) of the page


### Get layout for a page [GET]

+ Response 200 (application/json)

    + Headers


    + Body

            { "abc": "def" }


# Group iOS
iOs related resources

# Group WebClient
WebClient related resources

# Group AppleTV
AppleTV related resources

# Group Common/Backing 
Common resources that will be backing the client adapters

